### PR TITLE
Fixed password prompt in windows

### PR DESCRIPTION
**Pull request by nitso**

### CODE REVIEW

**Comment by nitso** [comment]
Dupe of https://github.com/kohana/minion/pull/95 into develop branch

**Comment by evanpurkhiser** [comment]
Hmm. Was this already fixed in affb9bf57e8e43bce443d5bf618c5e828fac49b4?

**Comment by nitso** [comment]
Nope. You have to exec vbscript, but not a message ;)

**Comment by nitso** [comment]
hey ping!
Any problems with this one?

**Comment by evanpurkhiser** [comment]
Looks good. Thanks!

**Pull request merged**
