### PR TITLE
Update Help.php

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by samwilson** [comment]
+1

**Comment by zeelot** [comment]
Thanks!

**Comment by WinterSilence** [comment]
@Zeelot what about https://github.com/kohana/minion/pull/90 ? it's obviously a bug

**Comment by zeelot** [comment]
It has to be resent to a develop branch then I can merge it

**Comment by WinterSilence** [comment]
@Zeelot  Send pull request to 3.4: https://github.com/kohana/minion/pull/91

**Pull request merged**
