### PR TITLE
Setup step is no longer needed

### PR DESCRIPTION
**Pull request by cwilsn**
Code is already included in 3.3

### CODE REVIEW

**Comment by zeelot** [comment]
Could you file tickets for you bugs and reference these pulls?

**Comment by cwilsn** [comment]
Ticket filed: http://dev.kohanaframework.org/issues/4645

**Comment by zeelot** [comment]
thanks :)

**Comment by lenton** [comment]
This has been fixed here: https://github.com/kohana/minion/commit/7bee93401b5d6d9f8a6a2415dbb7568d19c50e1f

**Pull request closed without merging**
