### PR TITLE
Feature/cleanup

### PR DESCRIPTION
**Pull request by zeelot**
Just trying to clean things up and match a little closer to what they used to be.
- Removed last `Util` methods. Had to keep a couple static ones for now but at least they are all in `Minion_Task` where they belong
- Validation method for valid options was also moved to `Minion_Task` as it's not useful anywhere else
- `$_options` is now a `$option => $default` array and defines the accepted options
- Moved static method/property order to match all our other code (we should discuss official conventions)
- Removed any left over notion of `config` since everything is `options` now

### CODE REVIEW

**Comment by zeelot** [comment]
@kiall could you give this a quick look? I think I am ok with minion being released in this state (would like to get rid of more static functions down the road)

**Comment by zeelot** [comment]
Guess I'll try fixing the build tomorrow ;) probably broken unit tests

**Comment by kiall** [comment]
Re the build failure.. From http://ci.kohanaframework.org/job/kohana-3.3-pull/64/consoleFull

```
PHP Fatal error:  Class 'Minion_Util' not found in /var/lib/jenkins/jobs/kohana-3.3-pull/workspace/modules/minion/tests/minion/util.php on line 48
```

Re the pull itself.. Looks good. Let's get this merged once the tests are sorted :)

**Comment by zeelot** [comment]
!build

**Comment by biakaveron** [comment]
Task_Help class still uses Minion_Util.

**Comment by zeelot** [comment]
Thanks I'll take a look!

**Comment by biakaveron** [comment]
See https://github.com/kohana/minion/pull/55

**Pull request merged**
