### PR TITLE
adding bash auto completion script, and new action to return a list of av

### PR DESCRIPTION
**Pull request by mintbridge**
First working go at adding bash auto completion script.

At the moment you have to put the first letter of the task name (in case there are a lot of tasks) and then tab but this could be changed easily so that tabbing without any initial letter would return all tasks

### CODE REVIEW

**Comment by zeelot** [comment]
Great, I was trying to do this as well so I will take a look at this next time I have a minute. Thanks :)

**Comment by zeelot** [comment]
It seems like this stuff is specific to OS/Distro and requires some manual work. What do you think about making an Ubuntu package that does this stuff and putting it on launchpad?

**Comment by mintbridge** [comment]
Yeah sounds like a good idea, never done it before though so I'll have to it out first...

**Comment by zeelot** [comment]
Alright, I am trying to release 1.0.0 soon so I will get all the little API breaks and release that. Then we can focus on this autocomplete stuff. I've never done packages either so this is going to be fun =P

I am an Ubuntu user so I would probably start there but we can provide things for a few of the major Distros

**Comment by mintbridge** [comment]
Yep should be fun. I'm away on holiday for a week but will have a look when I get back. I'm on Ubuntu as well.

**Pull request closed without merging**
